### ISSUE TITLE
Configure Pylint for Code Quality Assurance

### ISSUE THREAD

**Issue by Ymmy833y** [Ymmy833y/duplicate-issue-checker#2]
## Todo

- [x] Add Pylint as a dependency in the development environment.
- [x] Create and configure the .pylintrc file with project-specific rules.
- [x] Add a Pylint step to the CI pipeline for automated code quality checks.
